name: Publish

on:
  workflow_run:
    workflows: ["run-tests"]
    types: [completed]
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 14

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Upload Artifacts
        run: |
          ./gradlew clean publish --stacktrace
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}